### ISSUE TITLE
Moving to Torchbearer 2E

### ISSUE THREAD

**Issue by sharrap** [lupinelegend/torchbearer#94]
I'm currently in the process of updating the inventory system to support Torchbearer 2E. Do you have strong feelings about keeping backwards compatibility with Torchbearer 1E?

My initial feeling is that we should drop backwards compat: I don't foresee any great opposition to people moving to 2E (it's basically a patch on the same game with new content, after all) and there are a lot of minor inconsistencies that would make the code a lot more complicated if we support both. We also have a 1.1.0 release which 1E people can use. If we get to the point where we've added a bunch of new features (e.g. enhanced monster sheets, camp sheet, conflict sheet ...) and want to bring those back into Torchbearer 1E, we can also work on retroactively adding back compatibility if there's a strong demand, saving time in the meantime and hopefully avoiding that ever being necessary.

Keeping support for 1E also means having to figure out how to manage the compendiums.

**Comment by lupinelegend** [comment]
I agree, no need for backwards compatibility.
